//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury_z_podziałem_na_Kategorie
    {
        public string Nazwa { get; set; }
        public string Numer { get; set; }
        public decimal DoZaplaty { get; set; }
        public Nullable<decimal> Zaplacono { get; set; }
    }
}
