//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmy_z_iloscia_faktur
    {
        public int FirmaID { get; set; }
        public string NazwaFirmy { get; set; }
        public Nullable<int> Ilość_Faktur { get; set; }
    }
}
