//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci_Z_Maks_Kwota_DO_Zaplaty
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<decimal> Kwota_do_zapłaty { get; set; }
    }
}
