//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmy()
        {
            this.Faktury = new HashSet<Faktury>();
        }
    
        public int FirmaID { get; set; }
        public string NazwaFirmy { get; set; }
        public string NIP { get; set; }
        public string Regon { get; set; }
        public string Kraj { get; set; }
        public string Miasto { get; set; }
        public string Adres { get; set; }
        public string KodPocztowy { get; set; }
        public string NazwaBanku { get; set; }
        public string NumerKontaBank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
    }
}
