//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liczebniki
    {
        public string Rzad { get; set; }
        public int Value { get; set; }
        public string Liczebnik { get; set; }
    }
}
